'use client';
import {useMemo,useState} from 'react';

type Shot={title:string;duration:string;camera:string;action:string;lighting:string;say:string};
const shots:Shot[]=[
{title:'Stop the scroll',duration:'2 sec',camera:'Close-up · vertical',action:'Start with the product just outside frame, then bring it quickly toward the lens.',lighting:'Face a window. Keep the light soft and even.',say:'“Why is nobody talking about this?”'},
{title:'Reveal the product',duration:'2 sec',camera:'Close-up · steady',action:'Hold the label toward the camera and keep it centered.',lighting:'Turn slightly to avoid glare.',say:'No dialogue — use this as B-roll.'},
{title:'Show one detail',duration:'3 sec',camera:'Extreme close-up',action:'Slowly move across the packaging or most interesting product detail.',lighting:'Use brighter side light for texture.',say:'“This is what caught my attention.”'},
{title:'Demonstrate it',duration:'4 sec',camera:'Medium close-up',action:'Show the product being used naturally. Keep the main action in the middle of frame.',lighting:'Bright, even light.',say:'Explain the main benefit in one short sentence.'},
{title:'Make the benefit clear',duration:'3 sec',camera:'Face + product',action:'Hold the product beside you and give a natural reaction.',lighting:'Keep your face toward the light.',say:'“The best part is how simple it is to use.”'},
{title:'Finish with a CTA',duration:'3 sec',camera:'Eye-level close-up',action:'Keep the product clearly visible and look into the lens.',lighting:'Match the first shot.',say:'“If you’ve been looking for one, check this out.”'}];
const goals=['Viral / Attention','Sell My Product','UGC Style','Product Showcase','Problem → Solution'];
export default function Home(){
 const [view,setView]=useState<'home'|'dashboard'|'create'|'ideas'|'director'|'done'>('home');
 const [name,setName]=useState(''); const [point,setPoint]=useState(''); const [goal,setGoal]=useState(goals[0]); const [image,setImage]=useState<string>(); const [shot,setShot]=useState(0);
 const ideas=useMemo(()=>[
 {hook:`Why is nobody talking about ${name||'this'}?`,desc:`A curiosity-first ${goal.toLowerCase()} video that reveals the product and demonstrates ${point||'its main benefit'}.`},
 {hook:`I didn’t expect ${name||'this product'} to be this good.`,desc:'A natural phone-shot recommendation that feels like a friend sharing a discovery.'},
 {hook:`Watch this before you buy another one.`,desc:'A fast problem-to-product concept built around one clear reason to care.'}], [name,point,goal]);
 function pickFile(f?:File){if(f){const r=new FileReader();r.onload=()=>setImage(String(r.result));r.readAsDataURL(f)}}
 const nav=<nav><button className="logo" onClick={()=>setView('home')}>Shoot<span>AI</span></button><button className="navbtn" onClick={()=>setView('dashboard')}>Dashboard</button></nav>;
 if(view==='home') return <main>{nav}<section className="hero"><div><div className="badge">AI PRODUCT FILMING DIRECTOR</div><h1>Don’t know how to film your product?</h1><p className="lead">Show ShootAI what you sell. Get a content concept and exact shot-by-shot instructions you can follow with your phone.</p><button className="cta" onClick={()=>setView('create')}>Create a filming plan →</button><p className="tiny">No video generation. No editing. Just clear direction.</p></div><div className="mock"><div className="phone"><div className="frame"><div className="box">YOUR<br/>PRODUCT</div><span>✓ Great framing</span></div><small>SHOT 1 OF 6 · HOOK</small><b>Bring the product quickly toward the camera.</b></div></div></section><section className="how"><p>HOW IT WORKS</p><h2>From product to shot list in minutes.</h2><div className="steps"><article><i>01</i><h3>Show your product</h3><span>Upload a photo and tell us the key selling point.</span></article><article><i>02</i><h3>Pick a concept</h3><span>ShootAI gives you simple short-form content directions.</span></article><article><i>03</i><h3>Follow the director</h3><span>Film one shot at a time with camera, action, lighting and dialogue guidance.</span></article></div></section></main>;
 if(view==='dashboard') return <main>{nav}<section className="page"><div className="row"><div><div className="badge">YOUR WORKSPACE</div><h2>Projects</h2></div><button className="cta small" onClick={()=>setView('create')}>+ New project</button></div><div className="empty"><div>◎</div><h3>Your first product video starts here.</h3><p>Create a project and ShootAI will plan every shot for you.</p><button className="cta small" onClick={()=>setView('create')}>Create project →</button></div></section></main>;
 if(view==='create') return <main>{nav}<section className="page narrow"><button className="back" onClick={()=>setView('dashboard')}>← Dashboard</button><div className="badge">NEW PROJECT</div><h2>What are you filming?</h2><p>Give ShootAI enough context to create a useful plan.</p><label className="upload"><input type="file" accept="image/*" onChange={e=>pickFile(e.target.files?.[0])}/>{image?<img src={image} alt="Product preview"/>:<><strong>＋</strong><b>Upload product photo</b><span>Click to choose an image</span></>}</label><label>Product name<input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Papaya Soap"/></label><label>Main selling point<textarea value={point} onChange={e=>setPoint(e.target.value)} placeholder="What should customers know about it?"/></label><label>Video goal<div className="goalgrid">{goals.map(g=><button key={g} className={goal===g?'selected':''} onClick={()=>setGoal(g)}>{g}</button>)}</div></label><button className="cta full" onClick={()=>setView('ideas')}>Generate filming ideas ✦</button></section></main>;
 if(view==='ideas') return <main>{nav}<section className="page narrow"><button className="back" onClick={()=>setView('create')}>← Product details</button><div className="badge">3 CONCEPTS</div><h2>Choose a direction.</h2><p>Pick the concept you’d actually enjoy filming.</p><div className="cards">{ideas.map((x,i)=><article className={i===0?'idea best':'idea'} key={x.hook}>{i===0&&<em>BEST MATCH</em>}<small>15–20 SEC · EASY TO FILM</small><h3>“{x.hook}”</h3><p>{x.desc}</p><div className="sequence">HOOK → REVEAL → DEMO → BENEFIT → CTA</div><button className="outline" onClick={()=>{setShot(0);setView('director')}}>Use this concept →</button></article>)}</div></section></main>;
 if(view==='director'){const s=shots[shot];return <main>{nav}<section className="page narrow"><button className="back" onClick={()=>setView('ideas')}>← Concepts</button><div className="progress"><i style={{width:`${(shot+1)/shots.length*100}%`}}/></div><div className="shotrow"><span>SHOT {shot+1} OF {shots.length}</span><span>{s.duration.toUpperCase()}</span></div><h2>{s.title}</h2><div className="visual"><div className="guide"></div>{image?<img src={image} alt="Your product"/>:<div className="box">PRODUCT</div>}<b>↑</b></div><div className="details"><div><small>CAMERA</small><strong>{s.camera}</strong></div><div><small>ACTION</small><strong>{s.action}</strong></div><div><small>LIGHTING</small><strong>{s.lighting}</strong></div></div><div className="say"><small>SAY</small><strong>{s.say}</strong></div><button className="cta full" onClick={()=>shot<shots.length-1?setShot(shot+1):setView('done')}>{shot<shots.length-1?'✓ Done — Next shot':'✓ Complete filming plan'}</button></section></main>}
 return <main>{nav}<section className="finish"><div className="tick">✓</div><div className="badge">FILMING PLAN COMPLETE</div><h2>You know exactly what to shoot.</h2><p>Follow your six shots while filming, then edit the footage in your preferred editor.</p><div className="donegrid">{['Hook','Product reveal','Detail shot','Demonstration','Main benefit','Call to action'].map(x=><div key={x}>✓ <span>{x}</span></div>)}</div><button className="cta" onClick={()=>{setName('');setPoint('');setImage(undefined);setView('create')}}>Create another plan →</button></section></main>;
}
